### ISSUE TITLE
pushing IngestInput-pprof failed invalid_argument

### ISSUE THREAD

**Issue by hawkingrei** [grafana/pyroscope-go#100]
I am working to make ```pyroscope-go``` into TiDB by https://github.com/pingcap/tidb/pull/52139. but I find this error message. and i cannot find CPU profiler in the dashboard.

```
[ERROR] upload profile: failed to upload. server responded with statusCode: '422' and body: '{"code":"unknown","message":"pushing IngestInput-pprof failed invalid_argument: invalid utf8 string hex: d614508c2ea7ff1e0af4842e2d811c1eac516ac461129cf1f89d17ec148fa780"}
```

**Comment by kolesnikovae** [comment]
Hi @hawkingrei, thank you for reporting the issue! Could you please collect a profile from a running TiDB instance using the built-in profiler and post it here? That would greatly help with the investigation. Also, could you please specify which Go version you're using?

**Comment by hawkingrei** [comment]
> Hi @hawkingrei, thank you for reporting the issue! Could you please collect a profile from a running TiDB instance using the built-in profiler and post it here? That would greatly help with the investigation. Also, could you please specify which Go version you're using?

We maybe find the roout cause of this problem. ref https://github.com/pingcap/tidb/issues/52215.

**Comment by korniltsev** [comment]
Let's close the issue. Feel free to reopen if you think there need to be changes/investigations on the `grafana/pyroscope-go` side
