### ISSUE TITLE
Question about when the profiled been collected

### ISSUE THREAD

**Issue by woodliu** [grafana/pyroscope-go#105]
Hi, I have a quesiton about the when to collect the profile.

- If the `ServerAddress` in [Profiling Go applications](https://github.com/grafana/pyroscope-go?tab=readme-ov-file#profiling-go-applications) is down, does it still collect the profile and trying to send them to the server?
- If there is no collector to pull the profile in [pull mode](https://github.com/grafana/pyroscope-go?tab=readme-ov-file#pull-mode), does still collect the profile?

Thanks

**Comment by kolesnikovae** [comment]
Hey @woodliu, thanks for addressing the issue!

* Yes, if the specified server is not available, the profiler will still collect profiles.
* No, profile collection is initiated by a "push" request. Without it, no profiles are collected.

**Comment by woodliu** [comment]
> Hey @woodliu, thanks for creating the issue!
> 
> * Yes, if the specified server is not available, the profiler will still collect profiles.
> * No, profile collection is initiated by a "pull" request. Without it, no profiles are collected.

Thanks kolesnikovae, that very helpful
