### ISSUE TITLE
How to set cpu sample rate

### ISSUE THREAD

**Issue by ray2011** [grafana/pyroscope-go#17]
```
func (ps *Session) uploadData(startTime, endTime time.Time) {
	if ps.isCPUEnabled() {
		pprof.StopCPUProfile()
		defer func() {
			pprof.StartCPUProfile(ps.cpuBuf)
		}()
		ps.upstream.Upload(&upstream.UploadJob{
			Name:            ps.appName,
			StartTime:       startTime,
			EndTime:         endTime,
			SpyName:         "gospy",
			SampleRate:      100,
			Units:           "samples",
			AggregationType: "sum",
			Format:          upstream.FormatPprof,
			Profile:         copyBuf(ps.cpuBuf.Bytes()),
		})
		ps.cpuBuf.Reset()
	}
    //........
}
```
Now:
No matter what `config.SimpleRate` is,  cpu profile was always turned on after last uploadData finish.

**Comment by korniltsev** [comment]
It is hard to do in a clean way with the current go stdlib https://cs.opensource.google/go/go/+/refs/tags/go1.22.5:src/runtime/pprof/pprof.go;l=821

It is  not impossible, we used to have a fork of the piece of stdlib https://github.com/grafana/pyroscope/tree/og/pkg/agent/pprof which used to work. But we do not maintain it.

Some more links for context/tracking:
https://github.com/golang/go/issues/42502
https://github.com/golang/go/issues/57488
