### ISSUE TITLE
Consider moving godeltaprof to this repository

### ISSUE THREAD

**Issue by kolesnikovae** [grafana/pyroscope-go#42]
In the same way [we changed the import path of the client package](https://github.com/grafana/pyroscope-go/pull/39) we should do the same for https://github.com/grafana/godeltaprof, which is currently imported as `github.com/pyroscope-io/godeltaprof`.

As an option, we should consider moving the package into this repository into a sub-module (to avoid unnecessary dependencies)

**Comment by cyriltovena** [comment]
I would definitively go for moving the package !
